name: Build Quarto site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Quarto
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: latest

      # 4️⃣ Construire le site
      - name: Build site
        run: quarto render

      # 5️⃣ Sauvegarder le dossier généré (_site)
      - name: Upload built site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
